name: CI/CD FocusCRM - Grupo F

on:
  push:
    branches: [ "main" ] # Se activa cuando subes cambios a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: luisstrdocker/focus-crm:latest